# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
version: 2
updates:
  # Enable updates for Github Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
  # Enable updates for Cargo
  - package-ecosystem: "cargo"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
  # Enable updates for Python (pyproject.toml)
  - package-ecosystem: "pip"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
