from __future__ import annotations

import sys
from typing import Any
from collections.abc import Callable, Awaitable

from ._types import WebsocketMessage
from .http import HTTP1Settings, HTTP2Settings

__version__: str
BUILD_GIL: bool

class App:
    def __init__(
        self,
        on_request: Callable[[Any, Any], None],
        on_websocket: Callable[[Any, Any], None],
    ) -> None: ...

class AbortHandle:
    def __call__(self) -> None: ...

class RSGIHeaders:
    def __contains__(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def get(self, key: str, default: Any = None) -> Any: ...

class RSGIHTTPReader:
    def read(self, on_data: Callable[[bytes, bool], None]) -> AbortHandle: ...
    def _read_asyncio(self) -> Awaitable[tuple[bytes, bool]]: ...

class RSGIHTTPWriter:
    def write_bytes(self, data: bytes, on_done: Callable[[], None], on_error: Callable[[], None]) -> AbortHandle: ...
    def write_str(self, data: str, on_done: Callable[[], None], on_error: Callable[[], None]) -> AbortHandle: ...
    def _write_asyncio_bytes(self, data: bytes) -> Awaitable[None]: ...
    def _write_asyncio_str(self, data: str) -> Awaitable[None]: ...

class RSGIHTTPProtocol:
    def close(self) -> None: ...
    def read(self, on_data: Callable[[bytes], None], on_error: Callable[[], None]) -> AbortHandle | None: ...
    def reader(self) -> RSGIHTTPReader: ...
    def watch(self, on_disconnect: Callable[[], None]) -> AbortHandle | None: ...
    def write(self, status: int, headers: list[tuple[str, str]]) -> None: ...
    def write_str(self, status: int, headers: list[tuple[str, str]], body: str) -> None: ...
    def write_bytes(self, status: int, headers: list[tuple[str, str]], body: bytes) -> None: ...
    def write_file(self, status: int, headers: list[tuple[str, str]], file: str) -> None: ...
    def write_file_range(
        self, status: int, headers: list[tuple[str, str]], file: str, start: int, end: int
    ) -> None: ...
    def writer(self, status: int, headers: list[tuple[str, str]]) -> RSGIHTTPWriter: ...
    def _read_asyncio(self) -> Awaitable[bytes]: ...
    def _watch_asyncio(self) -> Awaitable[None]: ...

class RSGIWebsocketReader:
    def read(self, on_data: Callable[[WebsocketMessage], None], on_error: Callable[[], None]) -> AbortHandle: ...
    def _read_asyncio(self) -> Awaitable[WebsocketMessage]: ...

class RSGIWebsocketWriter:
    def write_bytes(self, data: bytes, on_done: Callable[[], None], on_error: Callable[[], None]) -> AbortHandle: ...
    def write_str(self, data: str, on_done: Callable[[], None], on_error: Callable[[], None]) -> AbortHandle: ...
    def _write_asyncio_bytes(self, data: bytes) -> Awaitable[None]: ...
    def _write_asyncio_str(self, data: str) -> Awaitable[None]: ...

class RSGIWebsocketProtocol:
    def accept(
        self, on_accepted: Callable[[RSGIWebsocketReader, RSGIWebsocketWriter], None], on_error: Callable[[], None]
    ) -> AbortHandle: ...
    def close(self, status: int | None = None) -> tuple[int, bool]: ...
    def _accept_asyncio(self) -> Awaitable[tuple[RSGIWebsocketReader, RSGIWebsocketWriter]]: ...

class RSGIProtocolError(RuntimeError): ...
class RSGIProtocolClosed(RuntimeError): ...

class WSGIScope:
    def to_environ(self, environ: dict[str, Any]) -> dict[str, Any]: ...

class WorkerSignal:
    def __init__(self) -> None: ...
    def set(self) -> None: ...
    def add_cb(self, cb: Any) -> None: ...

class ASGIWorker:
    def __new__(
        cls,
        worker_id: int,
        sock: Any,
        threads: int,
        blocking_threads: int,
        py_threads: int,
        py_threads_idle_timeout: int,
        py_loopback_thread: bool,
        backpressure: int,
        http_mode: str,
        http1_opts: HTTP1Settings | None,
        http2_opts: HTTP2Settings | None,
        websockets_enabled: bool,
        static_files: tuple[str, str, str | None, str | None] | None,
        ssl_enabled: bool,
        ssl_cert: str | None,
        ssl_key: str | None,
        ssl_key_password: str | None,
        ssl_protocol_min: str,
        ssl_ca: str | None,
        ssl_crl: list[str],
        ssl_client_verify: bool,
    ) -> ASGIWorker: ...

class RSGIWorker:
    def __new__(
        cls,
        worker_id: int,
        sock: Any,
        threads: int,
        blocking_threads: int,
        py_threads: int,
        py_threads_idle_timeout: int,
        py_loopback_thread: bool,
        backpressure: int,
        http_mode: str,
        http1_opts: HTTP1Settings | None,
        http2_opts: HTTP2Settings | None,
        websockets_enabled: bool,
        static_files: tuple[str, str, str | None, str | None] | None,
        ssl_enabled: bool,
        ssl_cert: str | None,
        ssl_key: str | None,
        ssl_key_password: str | None,
        ssl_protocol_min: str,
        ssl_ca: str | None,
        ssl_crl: list[str],
        ssl_client_verify: bool,
    ) -> RSGIWorker: ...

class WSGIWorker:
    def __new__(
        cls,
        worker_id: int,
        sock: Any,
        threads: int,
        blocking_threads: int,
        py_threads: int,
        py_threads_idle_timeout: int,
        py_loopback_thread: bool,
        backpressure: int,
        http_mode: str,
        http1_opts: HTTP1Settings | None,
        http2_opts: HTTP2Settings | None,
        static_files: tuple[str, str, str | None, str | None] | None,
        ssl_enabled: bool,
        ssl_cert: str | None,
        ssl_key: str | None,
        ssl_key_password: str | None,
        ssl_protocol_min: str,
        ssl_ca: str | None,
        ssl_crl: list[str],
        ssl_client_verify: bool,
    ) -> WSGIWorker: ...

class SocketHolder:
    def get_fd(self) -> Any: ...
    def is_uds(self) -> bool: ...

class ListenerSpec:
    def __new__(cls, host: str, port: int, backlog: int) -> ListenerSpec: ...
    def build(self) -> SocketHolder: ...
    def is_uds(self) -> bool: ...

if sys.platform != 'win32':
    class UnixListenerSpec:
        def __new__(cls, bind: str, backlog: int, permissions: int | None) -> UnixListenerSpec: ...
        def build(self) -> SocketHolder: ...
        def is_uds(self) -> bool: ...

class ProcInfoCollector:
    def __init__(self) -> None: ...
    def memory(self, pids: list[int] | None = None) -> int: ...

class IPCReceiverHandle:
    def __init__(self, id: int, fd: int): ...
    def run(self): ...

class IPCSenderHandle:
    def __init__(self, fd: int): ...

class MetricsAggregator:
    def __init__(self, size: int): ...
    def incr_spawn(self, val: int): ...
    def incr_respawn_err(self, val: int): ...
    def incr_respawn_ttl(self, val: int): ...
    def incr_respawn_rss(self, val: int): ...

class MetricsExporter:
    def __init__(self, aggregator: MetricsAggregator): ...
    def run(self, sock: SocketHolder, sig: WorkerSignal): ...
